### ISSUE TITLE
Unable to run/build on IOS

### ISSUE THREAD

**Issue by Philip-Nunoo** [LGro/coagulate#43]
After following the Guide within the readme, I noticed the app successfully run on android as opposed to IOS which I normally do work in.

When I run the app, I get the error:

```
Error (Xcode): could not compile `libsqlite3-sys` (lib) due to 1 previous error

Error (Xcode): could not compile `ring` (lib) due to 1 previous error
```

rustc --version  returns

```rustc --version ```

Flutter doctor also returns

```
Doctor summary (to see all details, run flutter doctor -v):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] IntelliJ IDEA Community Edition (version 2024.1.4)
[✓] VS Code (version 1.93.1)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

**Comment by LGro** [comment]
Thanks for your interest in Coagulate and apologies for the trouble building for iOS. As you might have seen, I'm only building iOS locally and not yet from CI/CD so there is an increased risk of something missing or being misaligned in the repo. I'll double check and let you know when it's worth to try again. Thanks for your patience ☺️

**Comment by Philip-Nunoo** [comment]
@LGro going to try figure it out, I do not believe it has something to do with your project. But for now, I believe I would get an android device and run the app. Great work on this as well.

**Comment by LGro** [comment]
If it's only for trying the app and not for development, I can also send you a TestFlight beta invite if you reach out to me directly via mail at lukas{at}grossberger.xyz or matrix @LuGro:matrix.org

**Comment by Philip-Nunoo** [comment]
Resolved:

For anyone having the same issue as above. There are two changes that I made in my case to  resolve the issue.

## change 1
During ```./dev-setup/setup_macos.sh``` 

java 17 is required for installation: see https://gitlab.com/veilid/veilid/-/blob/main/dev-setup/setup_macos.sh?ref_type=heads#L120-126

Even though my java version returns
```
java --version
openjdk version "23" 2024-09-17
OpenJDK Runtime Environment Homebrew (build 23)
OpenJDK 64-Bit Server VM Homebrew (build 23, mixed mode, sharing)
``` 

Updating the above line to 

```
# ensure Java 17 and above is installed
JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d\" -f2)
if [[ ! -z $(echo $JAVA_VERSION | egrep "^1[7-9]|^[2-9][0-9]") ]]; then
    echo '[X] Java 17 or higher is available in the path'
else
    echo 'Java 17 or higher is not available in the path'
    exit 1
fi
```

Enables installation for java version above 17

**Comment by LGro** [comment]
Thanks @Philip-Nunoo! If you face the same issue when building https://gitlab.com/veilid/veilidchat, consider letting the Veilid folks know about that potential fix as well.
I'm looking forward to handling Veilid more like a regular dependency when it is published to pub.dev and ensure the setup instructions for Coagualte are more self contained ☺️
